#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
analyze_all_models.py — analyze ProtBERT sliding-window occlusion results

What this does
--------------
Given a root folder of sliding-window results produced by
`apply_sliding_window_to_all_protbert.py`, this script:

  1) Iterates over all model_* subdirectories
  2) Loads sliding results (effects_by_window, window_sizes, etc.)
  3) For each window size:
       - Aggregates occlusion effects across all sequences and positions
       - Ranks per-residue effects
       - Computes amino-acid–level enrichment in:
            * Top fraction of (most positive) effects
            * Bottom fraction of (most negative) effects
       - Computes mean/std effect per amino acid
  4) Optionally saves full per-residue effect matrices for each model+window
  5) Writes per-model, per-window CSVs and a global summary CSV.

Assumptions
-----------
- The sliding-window results were generated by `apply_sliding_window_to_all_protbert.py`
  and stored under something like:
      results_root/model_1/
      results_root/model_2/
      ...
- Each model directory contains either:
    (a) a .npz file with keys including 'effects_by_window'
        and optionally 'window_sizes', or
    (b) a pickle file containing a dict or list named 'effects_by_window'
- The number and order of sequences align with the rows in seq_csv
  (i.e., the same CSV passed to apply_sliding_window_to_all_protbert.py).

CLI example
-----------
python3 analyze_all_models.py \
  --results_root protbert_sliding_results_top5 \
  --seq_csv /Users/zmrao/Desktop/Mofrad_Lab/IDPRg/data/allNormalizedNaive.csv \
  --sequence_col "Protein Sequence" \
  --target_col "Normalized Rg with ν = 0.5 (nm)" \
  --out_dir protbert_sliding_summary_top5 \
  --top_frac 0.15 \
  --bottom_frac 0.15 \
  --save_matrix_csv \
  --debug
"""

import os
import argparse
import json
import pickle
from pathlib import Path
from typing import Dict, Any, List, Tuple

import numpy as np
import pandas as pd


AA = list("ACDEFGHIKLMNPQRSTVWY")
AA_SET = set(AA)


# ------------------------------
# Loading utilities
# ------------------------------

def load_sliding_results(model_dir: str, debug: bool = False) -> Dict[str, Any]:
    """
    Try to load sliding-window results from a model directory.

    We attempt several formats:
      1) sliding_results.npz
      2) results.npz
      3) sliding_results.pkl
      4) effects_by_window.pkl

    Returns a dict with keys:
      - 'effects_by_window': list or array of per-window effect matrices
      - 'window_sizes': list of ints (if available, otherwise 1..len)
    """
    model_dir = Path(model_dir)

    # 1) Try NPZ formats
    for fname in ["sliding_results.npz", "results.npz"]:
        path = model_dir / fname
        if path.exists():
            if debug:
                print(f"[debug] Loading NPZ results from {path}")
            data = np.load(path, allow_pickle=True)
            keys = list(data.keys())
            if debug:
                print(f"[debug] NPZ keys: {keys}")

            # Try to pull effects_by_window
            if "effects_by_window" in data:
                effects_by_window = data["effects_by_window"]
            else:
                # Some variants might store effects under another key; if so,
                # you can adjust here if needed.
                raise KeyError(
                    f"'effects_by_window' not found in {path}. Keys: {keys}"
                )

            # window sizes, if present
            if "window_sizes" in data:
                window_sizes = list(data["window_sizes"])
            elif "windows" in data:
                window_sizes = list(data["windows"])
            else:
                # default: assume windows 1..len(effects_by_window)
                window_sizes = list(range(1, len(effects_by_window) + 1))

            return {
                "effects_by_window": effects_by_window,
                "window_sizes": window_sizes,
            }

    # 2) Try PKL formats
    for fname in ["sliding_results.pkl", "effects_by_window.pkl"]:
        path = model_dir / fname
        if path.exists():
            if debug:
                print(f"[debug] Loading PKL results from {path}")
            with open(path, "rb") as f:
                obj = pickle.load(f)

            if isinstance(obj, dict):
                # Expect a dict with 'effects_by_window' inside
                if "effects_by_window" in obj:
                    effects_by_window = obj["effects_by_window"]
                else:
                    # If the dict itself IS the effects_by_window, treat it as such
                    effects_by_window = obj

                # window sizes if present
                if "window_sizes" in obj:
                    window_sizes = list(obj["window_sizes"])
                elif "windows" in obj:
                    window_sizes = list(obj["windows"])
                else:
                    window_sizes = list(range(1, len(effects_by_window) + 1))
            else:
                # obj itself is the list/array of effects_by_window
                effects_by_window = obj
                window_sizes = list(range(1, len(effects_by_window) + 1))

            return {
                "effects_by_window": effects_by_window,
                "window_sizes": window_sizes,
            }

    raise FileNotFoundError(
        f"No recognizable sliding results found in {model_dir} "
        f"(expected .npz or .pkl with 'effects_by_window')."
    )


# ------------------------------
# Core analysis
# ------------------------------

def collect_effects_for_window(
    effects_win,
    sequences: List[str],
    debug: bool = False,
) -> List[Tuple[str, float]]:
    """
    Convert per-sequence, per-position effects for a given window into a flat list
    of (AA, effect) pairs.

    Supports:
        - effects_win as a 2D numpy array of shape (n_seq, Lmax)
        - effects_win as a list of 1D arrays (one per sequence)
    """
    aa_effects: List[Tuple[str, float]] = []

    # Case 1: list/array of per-sequence arrays
    if isinstance(effects_win, (list, tuple)):
        if debug:
            print(f"[debug] effects_win is list/tuple with len={len(effects_win)}")
        if len(effects_win) != len(sequences):
            if debug:
                print(
                    f"[warn] #sequences in effects ({len(effects_win)}) "
                    f"!= #sequences in seq_csv ({len(sequences)}). "
                    f"Using min of the two."
                )
        n = min(len(effects_win), len(sequences))
        for i in range(n):
            seq = sequences[i]
            eff = np.asarray(effects_win[i])
            L = min(len(seq), len(eff))
            for j in range(L):
                aa = seq[j]
                if aa in AA_SET:
                    aa_effects.append((aa, float(eff[j])))

    # Case 2: 2D numpy array (n_seq, Lmax)
    elif isinstance(effects_win, np.ndarray):
        if effects_win.ndim != 2:
            raise ValueError(
                f"effects_win is a numpy array but not 2D: shape={effects_win.shape}"
            )
        n_seq, Lmax = effects_win.shape
        if debug:
            print(f"[debug] effects_win is array with shape={effects_win.shape}")
        if n_seq != len(sequences):
            if debug:
                print(
                    f"[warn] #sequences in array ({n_seq}) "
                    f"!= #sequences in seq_csv ({len(sequences)}). "
                    f"Using min of the two."
                )
        n = min(n_seq, len(sequences))
        for i in range(n):
            seq = sequences[i]
            eff_row = effects_win[i, :]
            L = min(len(seq), eff_row.shape[0])
            for j in range(L):
                aa = seq[j]
                if aa in AA_SET:
                    aa_effects.append((aa, float(eff_row[j])))

    else:
        raise TypeError(
            f"Unsupported type for effects_win: {type(effects_win)}. "
            f"Expected list/tuple or 2D numpy array."
        )

    return aa_effects


def compute_enrichment(
    aa_effects: List[Tuple[str, float]],
    top_frac: float,
    bottom_frac: float,
) -> Tuple[pd.DataFrame, Dict[str, float]]:
    """
    Given a list of (AA, effect) across all sequences/positions for one model+window,
    compute:

      - per-AA mean & std effect
      - top/bottom fraction enrichment (log2 fold vs global AA frequency)

    Returns:
      df: DataFrame indexed by AA with columns:
            ['count_all', 'mean_effect', 'std_effect',
             'count_top', 'freq_top', 'count_bottom', 'freq_bottom',
             'global_freq', 'log2_enrich_top', 'log2_enrich_bottom']

      summary_stats: dict with some global stats (optional use)
    """
    if len(aa_effects) == 0:
        raise ValueError("No (AA, effect) pairs provided to compute_enrichment().")

    # Convert to DataFrame
    df_all = pd.DataFrame(aa_effects, columns=["AA", "effect"])

    # Global frequencies & basic stats
    total = len(df_all)
    global_counts = df_all["AA"].value_counts().reindex(AA, fill_value=0)
    global_freq = global_counts / total

    aa_mean = df_all.groupby("AA")["effect"].mean().reindex(AA)
    aa_std = df_all.groupby("AA")["effect"].std().reindex(AA)

    # Sort by effect
    df_sorted = df_all.sort_values("effect", ascending=False).reset_index(drop=True)

    # Determine top/bottom sizes
    top_n = max(1, int(len(df_sorted) * top_frac))
    bottom_n = max(1, int(len(df_sorted) * bottom_frac))

    df_top = df_sorted.iloc[:top_n]
    df_bottom = df_sorted.iloc[-bottom_n:]

    top_counts = df_top["AA"].value_counts().reindex(AA, fill_value=0)
    bottom_counts = df_bottom["AA"].value_counts().reindex(AA, fill_value=0)

    top_freq = top_counts / top_n
    bottom_freq = bottom_counts / bottom_n

    # Avoid division by zero
    eps = 1e-9
    log2_enrich_top = np.log2((top_freq + eps) / (global_freq + eps))
    log2_enrich_bottom = np.log2((bottom_freq + eps) / (global_freq + eps))

    out_df = pd.DataFrame(
        {
            "AA": AA,
            "count_all": global_counts.values,
            "global_freq": global_freq.values,
            "mean_effect": aa_mean.values,
            "std_effect": aa_std.values,
            "count_top": top_counts.values,
            "freq_top": top_freq.values,
            "count_bottom": bottom_counts.values,
            "freq_bottom": bottom_freq.values,
            "log2_enrich_top": log2_enrich_top.values,
            "log2_enrich_bottom": log2_enrich_bottom.values,
        }
    ).set_index("AA")

    summary_stats = {
        "total_points": int(total),
        "top_n": int(top_n),
        "bottom_n": int(bottom_n),
        "mean_effect_all": float(df_all["effect"].mean()),
        "std_effect_all": float(df_all["effect"].std()),
    }

    return out_df, summary_stats


# ------------------------------
# Main driver
# ------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--results_root", required=True,
        help="Root directory with per-model sliding-window results (e.g., protbert_sliding_results_top5)."
    )
    ap.add_argument(
        "--seq_csv", required=True,
        help="CSV containing the original sequences used for sliding-window analysis."
    )
    ap.add_argument(
        "--sequence_col", required=True,
        help="Column name in seq_csv containing protein sequences."
    )
    ap.add_argument(
        "--target_col", default=None,
        help="Optional: column name for true Rg (not required for enrichment, but stored in metadata)."
    )
    ap.add_argument(
        "--out_dir", required=True,
        help="Output directory for per-model and global summary CSVs."
    )
    ap.add_argument(
        "--top_frac", type=float, default=0.15,
        help="Fraction of (AA, effect) pairs to treat as 'top' (most positive)."
    )
    ap.add_argument(
        "--bottom_frac", type=float, default=0.15,
        help="Fraction of (AA, effect) pairs to treat as 'bottom' (most negative)."
    )
    ap.add_argument(
        "--min_window", type=int, default=None,
        help="Optional: minimum window size to include (default: no minimum)."
    )
    ap.add_argument(
        "--max_window", type=int, default=None,
        help="Optional: maximum window size to include (default: no maximum)."
    )
    ap.add_argument(
        "--save_matrix_csv", action="store_true",
        help="If set, save the per-position effect matrices as CSV for each model+window."
    )
    ap.add_argument(
        "--debug", action="store_true",
        help="Print extra debug information."
    )

    args = ap.parse_args()

    results_root = Path(args.results_root)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # --- Load sequence CSV ---
    df_seq = pd.read_csv(args.seq_csv)
    if args.sequence_col not in df_seq.columns:
        raise KeyError(
            f"sequence_col '{args.sequence_col}' not found in {args.seq_csv}. "
            f"Available columns: {list(df_seq.columns)}"
        )
    sequences = df_seq[args.sequence_col].astype(str).tolist()
    if args.debug:
        print(f"[debug] Loaded {len(sequences)} sequences from {args.seq_csv}")

    # Optional: target_col
    y_true = None
    if args.target_col is not None:
        if args.target_col not in df_seq.columns:
            raise KeyError(
                f"target_col '{args.target_col}' not found in {args.seq_csv}. "
                f"Available columns: {list(df_seq.columns)}"
            )
        y_true = df_seq[args.target_col].to_numpy()
        if args.debug:
            print(f"[debug] Loaded target column '{args.target_col}'")

    # --- Iterate over model directories ---
    model_dirs = sorted(
        [p for p in results_root.iterdir() if p.is_dir()],
        key=lambda p: p.name
    )
    if args.debug:
        print(f"[debug] Found {len(model_dirs)} model dirs under {results_root}")

    global_rows = []

    for mdir in model_dirs:
        model_name = mdir.name
        print(f"\n=== Analyzing {model_name} ===")

        try:
            loaded = load_sliding_results(mdir, debug=args.debug)
        except Exception as e:
            print(f"[warn] Skipping {model_name}: could not load results ({e})")
            continue

        effects_by_window = loaded["effects_by_window"]
        window_sizes = loaded["window_sizes"]

        # Some formats store this as numpy object array; turn into list
        if isinstance(effects_by_window, np.ndarray) and effects_by_window.dtype == object:
            effects_by_window = list(effects_by_window)

        if len(effects_by_window) != len(window_sizes):
            print(
                f"[warn] For {model_name}, len(effects_by_window)={len(effects_by_window)} "
                f"!= len(window_sizes)={len(window_sizes)}. "
                f"Using min of the two."
            )
        n_win = min(len(effects_by_window), len(window_sizes))

        model_json_meta = {}

        for idx in range(n_win):
            w = int(window_sizes[idx])

            if args.min_window is not None and w < args.min_window:
                continue
            if args.max_window is not None and w > args.max_window:
                continue

            print(f"  -> window={w}")

            effects_win = effects_by_window[idx]

            # Optionally save raw matrix for debugging/inspection
            if args.save_matrix_csv:
                matrix_out = out_dir / f"{model_name}_window{w}_matrix.csv"
                # Handle 2D array or list-of-arrays
                if isinstance(effects_win, np.ndarray) and effects_win.ndim == 2:
                    pd.DataFrame(effects_win).to_csv(matrix_out, index=False)
                elif isinstance(effects_win, (list, tuple)):
                    # Ragged -> save as json-lines-ish CSV: one row per sequence
                    # with variable length stored in JSON string
                    row_dict = {
                        "seq_idx": [],
                        "effects_json": [],
                    }
                    import json as _json
                    for i, arr in enumerate(effects_win):
                        row_dict["seq_idx"].append(i)
                        row_dict["effects_json"].append(_json.dumps(list(np.asarray(arr).tolist())))
                    pd.DataFrame(row_dict).to_csv(matrix_out, index=False)
                else:
                    # Fallback: attempt to coerce to array
                    pd.DataFrame(np.asarray(effects_win)).to_csv(matrix_out, index=False)

            # Collect (AA, effect) across all sequences/positions
            aa_effects = collect_effects_for_window(
                effects_win=effects_win,
                sequences=sequences,
                debug=args.debug,
            )

            if len(aa_effects) == 0:
                print(f"    [warn] No valid AA/effect pairs for {model_name}, window={w}; skipping.")
                continue

            df_enrich, stats = compute_enrichment(
                aa_effects,
                top_frac=args.top_frac,
                bottom_frac=args.bottom_frac,
            )

            # Save per-model, per-window AA enrichment CSV
            out_csv = out_dir / f"{model_name}_window{w}_aa_enrichment.csv"
            df_enrich.to_csv(out_csv)

            # Store in global list for summary
            for aa in df_enrich.index:
                row = {
                    "model": model_name,
                    "window": w,
                    "AA": aa,
                    "count_all": df_enrich.loc[aa, "count_all"],
                    "global_freq": df_enrich.loc[aa, "global_freq"],
                    "mean_effect": df_enrich.loc[aa, "mean_effect"],
                    "std_effect": df_enrich.loc[aa, "std_effect"],
                    "count_top": df_enrich.loc[aa, "count_top"],
                    "freq_top": df_enrich.loc[aa, "freq_top"],
                    "count_bottom": df_enrich.loc[aa, "count_bottom"],
                    "freq_bottom": df_enrich.loc[aa, "freq_bottom"],
                    "log2_enrich_top": df_enrich.loc[aa, "log2_enrich_top"],
                    "log2_enrich_bottom": df_enrich.loc[aa, "log2_enrich_bottom"],
                    "total_points": stats["total_points"],
                    "top_n": stats["top_n"],
                    "bottom_n": stats["bottom_n"],
                    "mean_effect_all": stats["mean_effect_all"],
                    "std_effect_all": stats["std_effect_all"],
                }
                global_rows.append(row)

            # Keep some per-window meta in JSON for quick glance if you want
            model_json_meta[f"window_{w}"] = stats

        # Optionally, write a small meta JSON for this model
        meta_path = out_dir / f"{model_name}_meta.json"
        with open(meta_path, "w") as f:
            json.dump(model_json_meta, f, indent=2)

    # --- Write global summary ---
    if len(global_rows) == 0:
        print("\n[warn] No data aggregated; no summary CSV written.")
        return

    df_global = pd.DataFrame(global_rows)
    summary_path = out_dir / "global_aa_enrichment_summary.csv"
    df_global.to_csv(summary_path, index=False)
    print(f"\n[done] Global AA enrichment summary written to: {summary_path}")


if __name__ == "__main__":
    main()